### ISSUE TITLE
Replace link to the NDJSON specification.

### ISSUE THREAD

**Issue by VeliKivilahti** [Azure-Samples/ai-chat-app-protocol#6]
The link currently in the documentation is no longer valid and should instead link to the specifications GitHub page https://github.com/ndjson/ndjson-spec or alternatively swap to only using the JSON Lines format https://jsonlines.org/, as NDJSON [seems to be heading towards deprecation ](https://github.com/ndjson/ndjson-spec/issues/35#issuecomment-1285673417)

**Comment by pamelafox** [comment]
Thanks, good catch. This repo has been superceded by https://github.com/microsoft/ai-chat-protocol/ so I have filed a PR there to fix it: https://github.com/microsoft/ai-chat-protocol/pull/49
I also put your suggestion to use JSON-lines. It'd be nice if we all decided on a single name/spec! :)
